import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import Hero from "~/components/Hero";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
      </main>
    </>
  );
};

export default Home;
